spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sakila
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: com.example.jpapractice.sakila.config.MySQLDialectCustom
        generate_statistics: true
  data:
    rest:
      base-path: /
      default-page-size: 10
      max-page-size: 50
      detection-strategy: annotated

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

