server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sakila?serverTimezone=Asia/Shanghai
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
#    show-sql: true
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        #        generate_statistics: true
        #        dialect: org.hibernate.dialect.MySQL8Dialect  # default
        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
        #        dialect: com.example.jpapractice.sakila.config.MySQLDialectCustom
        metadata_builder_contributor: com.example.jpapractice.sakila.config.SqlFunctionsMetadataBuilderContributor

  data:
    rest:
      base-path: /
      default-page-size: 10
      max-page-size: 50
      detection-strategy: annotated

  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging.level.org.hibernate.SQL: debug
#logging.level.org.hibernate.type.descriptor.sql: trace
